---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - JOBS=1

before_install:
  - yarn install
  - yarn --version

script:
  - yarn run lint:js
  - yarn test
  - yarn run coverage
